language: ruby
rvm:
- 2.0.0
- 2.1.5
- 2.2.0
env:
  global:
  - secure: awI4Vmf+oFJC8CToe+yZ7in2By5m290LFBhYNyMNVmZxSfSqS5eDTKOeCWltiA5bZmqEbV+lVxh7YkeBKeZFtUPiDflAXMV57pCDD/CKvThpxHMnCwOEhlBu6GbBbCXAvs+2oPtkIYRpkDaAwFPrUcNrnVwCrdLp7zaXgjpxC8Q=
  - secure: CuwWjtzRsPz4suem7KhRj7CVUEiscBUx7lMB+TEKi0zLeXtJNLsa6qvW866njDRBhw3kUD8jClmcKrAjLL/6/LUDXDdn83x6VEmcIK7yMQd3fR7OqhYnfu1OxDxzI+ed4hcA9UwYzdPIDBXCo/jNB3wDqyeDpLwTly+jtKh8tDE=
